POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvb3QiLCJpZCI6IjYzOGE2ZGJjZjUyYzIxMzBiMTIyZDFhOSIsImlhdCI6MTY3MDA4MjgwOH0.Nh7eziaQ-gdlW0bSh57Ltmptqes_UqnQTXPjumjgNCo

{
  "content": "Testing Authorization 2",
  "important": true
}